services:
  - type: web
    name: promptlink-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production

